# Generated by Django 5.0.6 on 2024-06-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=128, verbose_name='작성일'),
        ),
    ]
